### ISSUE TITLE
11월 3주차 회고

### ISSUE THREAD

**Issue by veluxer62** [veluxer62/veluxer62.github.io#492]

**Comment by veluxer62** [comment]
git multi command alias

```
fr = !git fetch --prune && git rebase origin/master
```

**Comment by veluxer62** [comment]
embeddable 클래스안에
ElementCollection 넣어도 부모 entity의 하위 자식으로 들어감

**Comment by veluxer62** [comment]
하지만 embeddable 클래스 안에 ElementCollection을 둘 경우 ElementCollection 값이 insert가 안된다 ㅡㅡ;;

```
@Embeddable
data class InventoryEmbed(
    @Column(name = "inventory_quantity", nullable = false)
    var quantity: Int,

    @Column(name = "inventory_minimum_quantity_for_notice", nullable = false)
    var minimumQuantityForNotice: Int,

    @Column(name = "inventory_limited", nullable = false)
    var isLimited: Boolean,

    @ElementCollection
    @CollectionTable(name = "kit_inventory_manual_change_histories", joinColumns = [JoinColumn(name = "kit_id")])
    var inventoryHistories: MutableList<InventoryManualChangeHistoryEmbed> = mutableListOf()
)
```

**Comment by veluxer62** [comment]
깃 이모지에 대한 글

https://pilgwon.github.io/post/gitmoji

**Comment by veluxer62** [comment]
openfeign

PageIml Jackson 시리얼라이즈 할려고 추가햇는데 원래 용도는 그게 아니엇음 추후 사용할 수도 있으니 검토

https://woowabros.github.io/experience/2019/05/29/feign.html

**Comment by veluxer62** [comment]
pageImpl 객체는 Jackson 직렬화시 오류가 발생.
아래와 같이 커스텀 클래스 만들어줘야함

근데 사용하지 않는 생성자 생기는거 좀 별로네

```
@JsonIgnoreProperties(ignoreUnknown = true)
class PageDto<T> : PageImpl<T> {
    @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
    constructor(
        @JsonProperty("content") content: List<T>,
        @JsonProperty("number") number: Int,
        @JsonProperty("size") size: Int,
        @JsonProperty("totalElements") totalElements: Long,
        @JsonProperty("pageable") pageable: JsonNode,
        @JsonProperty("last") last: Boolean,
        @JsonProperty("totalPages") totalPages: Int,
        @JsonProperty("sort") sort: JsonNode,
        @JsonProperty("first") first: Boolean,
        @JsonProperty("numberOfElement") numberOfElement: Int
    ) : super(content, PageRequest.of(number, size), totalElements)

    constructor(content: List<T>) : super(content)

    constructor(content: List<T>, pageable: Pageable, total: Long) : super(content, pageable, total)
}
```

**Comment by veluxer62** [comment]
transaction에서 pessimistic lock을 걸어도 연관테이블에서는 걸리지 않는다.
개별 table repository에 각각 걸어줘야함

**Comment by veluxer62** [comment]
jpa 잠금 타임아웃 설정
```
@Lock(LockModeType.PESSIMISTIC_WRITE) 
@QueryHints({@QueryHint(name = "javax.persistence.lock.timeout", value   ="5")}) 
```

단위는 초단위

**Comment by veluxer62** [comment]
elementcollection을 사용할때

데이터가 삭제되고 추가되는것을 방지하려면
1. ordercolumns를 추가한다 - 단점 order 컬럼이 생긴다, 다만 중복 데이터를 넣을 수 있다.
2. set 컬렉션을 사용한다 - 단점 중복데이터를 넣을 수 없다, 다만 order 컬럼을 넣지 않아도 된다.

**Comment by veluxer62** [comment]
에저 파이프라인에서 코드 커버리지를 확인할 수 있는 설정이 있다.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops


설정 예시

```
# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      codeCoverageToolOption: JaCoCo
      codeCoverageClassFilesDirectories: 'build/classes/kotlin/main/net/class101/inventory/'
      codeCoverageClassFilter: -:net.class101.inventory.infrastructure.config.*
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/class101-inventory-service/build/reports/jacoco/test/jacocoTestReport.xml
```
