### ISSUE TITLE
PR에 베이스 브런치 리베이스 해주는 GIT action

### ISSUE THREAD

**Issue by veluxer62** [veluxer62/veluxer62.github.io#538]
```yaml
on:
  pull_request:
    types:
    - labeled

jobs:
  rebase:
    if: >
      github.event.action == 'labeled' &&
      github.event.label.name == '이거 리베이스 해주세요'
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: 이름 설정
      env:
        NAME: '@${{ github.actor }}가 리베이스 함'
        EMAIL: dev+github-bot@spoqa.com
      run: |
        git config user.name "$NAME"
        git config user.email "$EMAIL"
        git config push.default simple
    - name: 리베이스
      env:
        REF_BASE: origin/${{ github.base_ref }}
        REF_HEAD: ${{ github.head_ref }}
        PR_NUM: ${{ github.event.number }}
      run: |
        if [ "$(git rev-parse "$REF_BASE")" = "$(git merge-base HEAD "$REF_BASE")" \
          -a "$(
            git log "$REF_BASE..HEAD" \
              --ancestry-path \
              --merges \
              --name-only \
              -n 1 \
              --oneline \
            2>/dev/null | wc -l
          )" = '0' \
        ]; then
          echo '✨ 리베이스 안 해도 된답니다 ✨'
        else
          echo '리베이스 중...'
          git rebase "$REF_BASE" &&
          git push --force-with-lease --set-upstream origin HEAD &&
          echo '🔧 리베이스 됨' || echo '⚠️ 리베이스 실패'
        fi
    - name: 🏷️ 라벨 지우기
      env:
        LABEL: ${{ github.event.label.name }}
        PR_NUM: ${{ github.event.number }}
        REPO: ${{ github.repository }}
      run: |
        curl --include -X DELETE \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          "https://api.github.com/repos/$REPO/issues/$PR_NUM/labels/$(
            node -pe 'encodeURIComponent(process.argv.pop())' "$LABEL"
          )"
```
